site_name: Основые языка SQL в СУБД Ред База Данных.

nav:
  - Введение:
    - Введение: '01_Introduction.md'
    - История БД: '02_History.md'
    - Модели данных: '03_DataModels.md'
    - Реляционная модель данных: '04_RelationalDataModel.md'
  - Проектировение БД:
    - ER-модель: '05_ERmodel.md'
    - Пример ER-модели: '06_ERexample.md'
    - Нормальные формы: '07_NormalForms.md'
  - Язык SQL:
    - Типы данных: '08_DataTypes.md'
    - Домены: '09_Domains.md'
    - Таблицы: '10_Tables.md'
    - Генераторы и последовательности: '11_Sequences.md'
    - Оператор SELECT: '12_Select.md'
    - Соединения: '13_Joins.md'
    - Фильтрация: '14_Where.md'
