site_name: Основые языка SQL в СУБД Ред База Данных.

nav:
  - Главная: 'index.md'
  - Введение:
    - Введение: '01_Introduction.md'
    - История БД: '02_History.md'
    - Модели данных: '03_DataModels.md'
    - Реляционная модель данных: '04_RelationalDataModel.md'
  - Проектировение БД:
    - ER-модель: '05_ERmodel.md'
    - Пример ER-модели: '06_ERexample.md'
    - Нормальные формы: '07_NormalForms.md'
  - Язык SQL:
    - Типы данных: '08_DataTypes.md'
